### ISSUE TITLE
theme_options.txt example

### ISSUE THREAD

**Issue by pixedelic** [FrankM1/radium-one-click-demo-install#22]
Sorry, may I see an example of how Radium's "theme_options.txt" is made? What's its structure? I use a framework made by me and I'm not sure to understand how this file should be compiled to be rightly imported.

I haven't tested your script yet, but as a ThemeForest author I really appreciate the fact you shared it, thank you so much.

Manuel :-)

**Comment by FrankM1** [comment]
Hi,

The theme_options.txt is the file generated by exporting theme options using redux, nhp or options framework. It is auto generated. You can look into those framework's source code to see how the file is created.

**Comment by pixedelic** [comment]
Thank you so much... doesn't Redux create a php file? However, I'll check. Thank you so much!

**Comment by FrankM1** [comment]
Alright. Redux generates a json file with the theme options nowadays.
