### ISSUE TITLE
Incompatibility with PHP 7.0.5

### ISSUE THREAD

**Issue by HornKild** [FrankM1/radium-one-click-demo-install#31]
Hello,

My theme use the Radium One Click Demo Install but it returns an error since I upgrade my hosting service with PHP 7.0.5, this is the error I have when trying to load page in the admin section 

` Fatal error: Redefinition of parameter $options in /htdocs/wp-content/themes/Fashion/radium-one-click-demo-install/importer/radium-importer.php on line 278`

What could be the workaround to make it works ?

Thank you,

Line 278 define the public function

```
/**
	     * Process all imports
	     *
	     * @params $content
	     * @params $options
	     * @params $options
	     * @params $widgets
	     *
	     * @since 0.0.3
	     *
	     * @return null
	     */
	    public function process_imports( $content = true, $options = true, $options = true, $widgets = true) {

			if ( $content && !empty( $this->content_demo ) && is_file( $this->content_demo ) ) {
				$this->set_demo_data( $this->content_demo );
			}

			if ( $options && !empty( $this->theme_options_file ) && is_file( $this->theme_options_file ) ) {
				$this->set_demo_theme_options( $this->theme_options_file );
			}

			if ( $options ) {
				$this->set_demo_menus();
			}

			if ( $widgets && !empty( $this->widgets ) && is_file( $this->widgets ) ) {
				$this->process_widget_import_file( $this->widgets );
			}

			do_action( 'radium_import_end');

        }
```

**Comment by Codevz** [comment]
Error says `Redefinition of parameter $options` so change this: 

`public function process_imports( $content = true, $options = true, $options = true, $widgets = true) {`

to this: 

`public function process_imports( $content = true, $options = true, $widgets = true) {`

**Comment by HornKild** [comment]
Thanks
