### ISSUE TITLE
What is the licence of this script?

### ISSUE THREAD

**Issue by primozcigler** [FrankM1/radium-one-click-demo-install#4]
Hi Frank,

I wonder how this script was licensed? I'd like to modify some code and change a repo structure a bit (with submodule to the original content import plugin etc.), but in order to do that, I need to know first how you decided to license your script, so I can give appropriate attribution.

Thank you for the answer!

**Comment by FrankM1** [comment]
I reviewed your code changes and they look pretty good. I'd be happy to merge them if you made a pull request. Sorry for the delay.

**Comment by primozcigler** [comment]
No problem. I will create a PR now, I am available to discuss any code changed I made if you'd want to.
