### ISSUE TITLE
Create Redux importer extension allowed?

### ISSUE THREAD

**Issue by Webcreations907** [FrankM1/radium-one-click-demo-install#7]
Hello,

First off thanks for providing this for others :smile: 

I see in another post that you had said it was ok to modify/fork/etc, I was curious if it would be ok for me to create a extension(free) for Reduxframework with it?

I've started on the creation of it and all seems to be working so far, but wanted to double check with you that it would be ok before wrapping it up. It's grown a bit more then I was planning in terms of features, but is simple to use.

Happy to provide more info if you'd like.

Thanks again :smile:

**Comment by Webcreations907** [comment]
Great thanks.
I'm working on wrapping that up now, will provide a bit more detail below.

- Auto loads demo data folders containing demo content, which gives ability to provide more than 1 demo data set/import option. No configuration is needed for demo folders/data. 

- Hooks/Filters through process so that other things can be done, example would be to import Revolution Slider import files, change demo data directory, etc :smile: 

- Add screenshot image for demos/imports

- Ajax Importing

- Themed to match admin profile color scheme using WP 'themes' layout.

Example demo data directory structure, 
```
demo-content-directory/
 - demo-1/
  -- content.xml
  -- etc
 - demo-2/
  -- content.xml
  -- etc
```

Screenshot of how it looks in theme options panel
![demo-importer](https://cloud.githubusercontent.com/assets/8421576/5591231/263fdfce-90fc-11e4-8d45-8631349bd375.jpg)

**Comment by pasqualevitiello** [comment]
Good idea @Webcreations907 ! Any progress on development?

**Comment by Webcreations907** [comment]
@pasqualevitiello Got a bit behind on projects, but am working on wrapping that up now :smile:

**Comment by pasqualevitiello** [comment]
Can't wait to test it!

**Comment by devskip** [comment]
Awesome job! waiting the release!

**Comment by FrankM1** [comment]
The implementation looks great. Can't wait to test it too.

**Comment by goranefbl** [comment]
That looks stunning! @Webcreations907 what is expected ETA for it?  :)

**Comment by Webcreations907** [comment]
Thanks 
@FrankM1, @pasqualevitiello , @devskip , @goranefbl 

Been swamped because of hosting issues(searching for new host) and ISP, so been a bit behind. 

Working on it though, going to get some example filters/functions together for setting menus, front page, importing rev slider, etc. Hoping that will be done/up on github Saturday. :smile:

**Comment by pasqualevitiello** [comment]
@Webcreations907 Great!

**Comment by Webcreations907** [comment]
@FrankM1, @pasqualevitiello , @devskip , @goranefbl 
It's Saturday! :smile:  Kinda late though.

Anyways link below, test that out and let me know what you all think, any questions, issues, etc. 
https://github.com/Webcreations907/WBC-Importer-extension

Thanks again @FrankM1

**Comment by FrankM1** [comment]
Good job @Webcreations907 on the release! Am testing it as we speak. :)

**Comment by Webcreations907** [comment]
@FrankM1 Thanks, let me if you have any questions. Can always Skype same username on there, if you'd like.

I wasn't sure if you wanted this topic closed or not, so will leave that up to you. :)

**Comment by devskip** [comment]
Awesome @Webcreations907! I'm going to test it, I will let you know! 

Thank you very much for sharing your time with us!

**Comment by FrankM1** [comment]
I think this is a good time to close this topic so that we can move the discussion over to the extension's page here https://github.com/Webcreations907/WBC-Importer-extension/issues

**Comment by dnbtheme** [comment]
content.xm exceed  2mb not working?
