### ISSUE TITLE
OptionTree integration

### ISSUE THREAD

**Issue by DanThemes** [FrankM1/radium-one-click-demo-install#8]
Hey,

Thanks for this plugin, it works great. Is there any way to generate a compatible "theme_options.txt" for the OptionTree?

**Comment by sabuz** [comment]
Same question here...

**Comment by FrankM1** [comment]
Get the new version. It supports option tree. Give it a spin and let me know.

**Comment by sabuz** [comment]
![image](https://cloud.githubusercontent.com/assets/7956101/6015072/3613d3d4-ab9a-11e4-9743-cc25cf65f488.png)

**Comment by FrankM1** [comment]
Hi, 

I think the content.xml is empty or missing. You will need to generate your own or use this one wptest.io

**Comment by FrankM1** [comment]
I presume it is working. I'll close this now.

**Comment by sabuz** [comment]
Everything is working correctly but theme options are not importing. Please help

**Comment by sabuz** [comment]
Working after adding these two line after line 407

$data = unserialize($data);
update_option( ot_options_id(), $data );
